USE documents;
ALTER TABLE `rejectlines` 	ADD COLUMN `CodeCr` VARCHAR(255) NULL DEFAULT NULL AFTER `Rejected`;
ALTER TABLE `rejectlines`	ADD COLUMN `OrderId` INT UNSIGNED NULL DEFAULT NULL AFTER `CodeCr`;