//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inforoom.PriceProcessor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PriceProcessorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PriceProcessorResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inforoom.PriceProcessor.PriceProcessorResource", typeof(PriceProcessorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;windows-1251&quot;?&gt;
        ///&lt;cml:schema xmlns:cml=&quot;http://www.w3.org/2001/XMLSchema&quot; version=&quot;2.021&quot;&gt;
        ///	&lt;!--Предусматривается использование данной схемы, в частности, для обмена:
        ///·	каталогами товаров; 
        ///·	коммерческими предложениями (прайс – листами); 
        ///·	документами, сопровождающими наиболее распространенные торговые (хозяйственные) операции :
        ///Заказ товара;
        ///Cчет на оплату;
        ///Отпуск товара;
        ///Счет-фактура;
        ///Возврат товара;
        ///Передача товара на комиссию;
        ///Возврат комиссионного товара;
        ///Отч [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommerceML {
            get {
                return ResourceManager.GetString("CommerceML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding = &quot;windows-1251&quot; standalone = &quot;yes&quot;?&gt;
        ///
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///
        ///	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; encoding=&quot;windows-1251&quot; /&gt;
        ///
        ///	&lt;xsl:template match=&quot;/&quot; &gt;
        ///		&lt;xsl:variable name=&quot;CodeCr&quot; select=&quot;КоммерческаяИнформация/ПакетПредложений/Ид&quot;/&gt;
        ///		
        ///		&lt;Price&gt;
        ///
        ///			&lt;xsl:for-each select=&quot;КоммерческаяИнформация/ПакетПредложений/Предложения/Предложение&quot;&gt;
        ///				&lt;Position&gt;
        ///					&lt;Code&gt;
        ///						&lt;xsl:value-of select=&quot;Ид&quot;/&gt;
        ///				 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PriceProtek {
            get {
                return ResourceManager.GetString("PriceProtek", resourceCulture);
            }
        }
    }
}
